version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: neobus-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: neobus
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - neobus-network

volumes:
  postgres_data:

networks:
  neobus-network:
    driver: bridge 